### PR TITLE
feat: use preferNoSetFee while signing with Keplr and chain is Evmos 

### PR DESCRIPTION
**Pull request by miliPaoletti**
This PR adds preferNoSetFee in order to use the fee created on the backend (for EVMOS Chain)
In the function `signBackendTxWithKeplr` was added a condition in order to use `preferNoSetFee` if the chain is Evmos. 
We are using it only for Evmos because the backend calculates the fee for that chain. If for example we want to Deposit Gravity, we'll pay the fee with Grav. That's why we don't set `preferNoSetFee` for other chains. 

We should merge this PR after https://github.com/evmos/backend/pull/140

We should merge this PR after https://github.com/evmos/apps/pull/254 and https://github.com/evmos/apps/pull/251

### CODE REVIEW

**Review by sandoche — COMMENTED** [review]
All good, but wait for the backend to be deployed before merging

**Comment by sandoche** [comment]
@miliPaoletti for the PR itself don't forget to update the version of all the apps and package you are editing and add it to the CHANGELOG.md :)

**Comment by miliPaoletti** [comment]
Can you please check @sandoche if I added it correctly? Thank you very much!

We should merge this PR after https://github.com/evmos/apps/pull/254 and https://github.com/evmos/apps/pull/251

**Review by Mrsirdev — APPROVED** [review]
🚀 

Looks good! I saw that @sandoche asked the keplr team in slack about this. Not sure if we want to wait for them to reply to merge or if we should go ahead and do it!

**Pull request merged**
