### PR TITLE
fix: show connected snackbar only if the user clicks on connect wallet

### PR DESCRIPTION
**Pull request by miliPaoletti**
Problem: Every time the user goes to a different page on the dashboard, the snackbar keeps coming up saying that my wallet is connected.

With this PR the connected snackbar will only appear if the user clicks on connect wallet button
Changes: 
- Disconnect button: add `RemoveProviderFromLocalStorage`
- Get the provider value from localStorage and compare it with the provider key. If they are the same, the snackbar will not show. 

https://user-images.githubusercontent.com/40247040/235127389-2a709a03-35d2-4af2-a743-adaf01736830.mov

### CODE REVIEW

**Comment by sandoche** [comment]
I did a test it looks good to me in terms of UI

cc @swankimz

**Comment by miliPaoletti** [comment]
Can you please check @sandoche if I added it correctly? Thank you very much!

**Comment by sandoche** [comment]
Yes it's good!

**Review by Mrsirdev — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
